# Generated by Django 5.0.6 on 2024-06-28 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_periodista', models.CharField(max_length=100)),
                ('titular', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('contenido_noticia', models.CharField(max_length=100)),
                ('imagen', models.ImageField(null=True, upload_to='img')),
            ],
        ),
    ]
