# Generated by Django 5.0.6 on 2024-07-08 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_usuario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Usuarioreg',
        ),
    ]
