# Generated by Django 5.0.6 on 2024-07-09 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_usuarioreg_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioreg',
            name='genero',
            field=models.IntegerField(choices=[(1, 'Masculino'), (2, 'Femenino'), (3, 'Otro')], default=1),
        ),
    ]
