# Generated by Django 5.0.6 on 2024-07-09 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_usuarioreg_genero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iniciosesion',
            old_name='usuario',
            new_name='username',
        ),
    ]
