# Generated by Django 5.0.6 on 2024-07-09 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_usuario_iniciosesion_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iniciosesion',
            old_name='username',
            new_name='usuario',
        ),
    ]
